# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_password
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      JWT_KEY: wenfwkjnwjwjwjj
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
