# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_USERNAME: testuser1
      DATABASE_PASSWORD: your_password
      DATABASE_NAME: bookstore
      JWT_KEY: wenfwkjnwjwjwjj
    ports:
      - '3306:3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
