version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_password
      MYSQL_TCP_PORT: 3306
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_password
      MYSQL_DATABASE: bookstore
      JWT_KEY: wenfwkjnwjwjwjj
    ports:
      - '3000:3000'
    depends_on:
      - mysql
